name: Pull Request
on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: build and test
      run: |
        ./gradlew build
    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v3
      if: always()
      with:
        report_paths: '**/build/test-results/*/TEST-*.xml'
    - name: Publish Test Report
      if: always()
      run: |
        find . -type f -regex ".*/build/.*/TEST-.*xml" 
        find . -type f -regex ".*/build/.*/TEST-.*xml" | xargs cat
        find . -type f -regex ".*/build/.*/TEST-.*xml" | xargs cat >> $GITHUB_OUTPUT
